package vibegrid

import (
	"errors"
	"net"
	"net/http"
	"net/netip"
	"strings"
)

const (
	maxPuzzleIDLength      = 96
	maxTileIDLength        = 96
	maxClientGuessIDLength = 128
)

var (
	ErrInvalidPuzzleID      = errors.New("puzzle id is invalid")
	ErrInvalidClientGuessID = errors.New("client guess id is invalid")
)

// validPublicIdentifier deliberately accepts the ids generated by editorial,
// community, and demo puzzles while refusing arbitrarily large or encoded path
// values before they can reach storage or observability code.
func validPublicIdentifier(value string, maxLength int) bool {
	if value == "" || len(value) > maxLength {
		return false
	}
	for _, char := range value {
		if (char >= 'a' && char <= 'z') || (char >= 'A' && char <= 'Z') || (char >= '0' && char <= '9') || char == '-' || char == '_' {
			continue
		}
		return false
	}
	return true
}

func validPuzzleID(value string) bool {
	return validPublicIdentifier(value, maxPuzzleIDLength)
}

// validateGuessRequest performs the cheap, storage-independent checks before an
// anonymous caller can allocate an attempt row. Membership validation remains in
// the store because it needs the authoritative puzzle content.
func validateGuessRequest(request GuessRequest) error {
	if !validPuzzleID(request.PuzzleID) {
		return ErrInvalidPuzzleID
	}
	if !validPublicIdentifier(request.ClientGuessID, maxClientGuessIDLength) {
		return ErrInvalidClientGuessID
	}
	if len(request.SelectedTileIDs) != GroupSize {
		return ErrInvalidGroupSize
	}

	seen := make(map[string]bool, GroupSize)
	for _, tileID := range request.SelectedTileIDs {
		if !validPublicIdentifier(tileID, maxTileIDLength) || seen[tileID] {
			return ErrInvalidGroupSize
		}
		seen[tileID] = true
	}
	return nil
}

// clientIdentity only honors forwarding headers from an explicitly configured
// reverse proxy. Every other caller is rate-limited by its socket peer address,
// preventing a public client from minting a new bucket with X-Real-IP.
type clientIdentity struct {
	trustedProxies []netip.Prefix
}

func newClientIdentity(rawCIDRs []string) clientIdentity {
	prefixes := make([]netip.Prefix, 0, len(rawCIDRs))
	for _, raw := range rawCIDRs {
		prefix, err := netip.ParsePrefix(strings.TrimSpace(raw))
		if err == nil {
			prefixes = append(prefixes, prefix.Masked())
		}
	}
	return clientIdentity{trustedProxies: prefixes}
}

func (identity clientIdentity) clientIP(r *http.Request) string {
	peer := remoteAddressIP(r.RemoteAddr)
	if peer.IsValid() && identity.isTrustedProxy(peer) {
		for _, value := range []string{
			r.Header.Get("Fly-Client-IP"),
			r.Header.Get("X-Real-IP"),
			strings.Split(r.Header.Get("X-Forwarded-For"), ",")[0],
		} {
			if forwarded, ok := parseClientIP(value); ok {
				return forwarded.String()
			}
		}
	}
	if peer.IsValid() {
		return peer.String()
	}
	return "unknown"
}

func (identity clientIdentity) isTrustedProxy(peer netip.Addr) bool {
	for _, prefix := range identity.trustedProxies {
		if prefix.Contains(peer) {
			return true
		}
	}
	return false
}

func remoteAddressIP(remoteAddr string) netip.Addr {
	host, _, err := net.SplitHostPort(strings.TrimSpace(remoteAddr))
	if err != nil {
		host = strings.TrimSpace(remoteAddr)
	}
	address, _ := netip.ParseAddr(host)
	return address.Unmap()
}

func parseClientIP(value string) (netip.Addr, bool) {
	address, err := netip.ParseAddr(strings.TrimSpace(value))
	if err != nil {
		return netip.Addr{}, false
	}
	return address.Unmap(), true
}
