package vibegrid

func SeedPuzzles() []Puzzle {
	return []Puzzle{
		{
			ID:           "vibegrid-2026-06-02",
			PuzzleNumber: 1,
			PublishDate:  "2026-06-02",
			Status:       PuzzleStatusPublished,
			Difficulty:   DifficultyMedium,
			Origin:       OriginEditorial,
			Groups: []PuzzleGroup{
				{
					ID:          "italian-summer",
					Name:        "Italian summer",
					Explanation: "A tiny holiday built from espresso, fabric, wheels, and sun.",
					ColorIndex:  0,
					Tiles: []Tile{
						{ID: "p1-espresso", Text: "espresso"},
						{ID: "p1-linen", Text: "linen"},
						{ID: "p1-vespa", Text: "Vespa"},
						{ID: "p1-balcony", Text: "balcony"},
					},
				},
				{
					ID:          "corporate-hostage-situation",
					Name:        "Corporate hostage situation",
					Explanation: "The meeting before the meeting, now with adrenaline.",
					ColorIndex:  1,
					Tiles: []Tile{
						{ID: "p1-slack", Text: "Slack"},
						{ID: "p1-deck", Text: "deck"},
						{ID: "p1-panic", Text: "panic"},
						{ID: "p1-959", Text: "9:59"},
					},
				},
				{
					ID:          "noir-evening",
					Name:        "Noir evening",
					Explanation: "A moody window scene with enough jazz to make the lamp suspicious.",
					ColorIndex:  2,
					Tiles: []Tile{
						{ID: "p1-rain", Text: "rain"},
						{ID: "p1-jazz", Text: "jazz"},
						{ID: "p1-window", Text: "window"},
						{ID: "p1-lamp", Text: "lamp"},
					},
				},
				{
					ID:          "gym-bro-morning",
					Name:        "Gym bro morning",
					Explanation: "Breakfast, recovery layer, and the sacred lift.",
					ColorIndex:  3,
					Tiles: []Tile{
						{ID: "p1-oats", Text: "oats"},
						{ID: "p1-whey", Text: "whey"},
						{ID: "p1-hoodie", Text: "hoodie"},
						{ID: "p1-deadlift", Text: "deadlift"},
					},
				},
			},
		},
		{
			ID:           "vibegrid-2026-06-03",
			PuzzleNumber: 2,
			PublishDate:  "2026-06-03",
			Status:       PuzzleStatusPublished,
			Difficulty:   DifficultyMedium,
			Origin:       OriginEditorial,
			Groups: []PuzzleGroup{
				{
					ID:          "airport-personality-collapse",
					Name:        "Airport personality collapse",
					Explanation: "The version of you that appears after security and before boarding.",
					ColorIndex:  0,
					Tiles: []Tile{
						{ID: "p2-passport", Text: "passport"},
						{ID: "p2-gate", Text: "gate"},
						{ID: "p2-neck-pillow", Text: "neck pillow"},
						{ID: "p2-boarding-group", Text: "boarding group"},
					},
				},
				{
					ID:          "fake-productivity-ritual",
					Name:        "Fake productivity ritual",
					Explanation: "A beautiful system for avoiding the actual task.",
					ColorIndex:  1,
					Tiles: []Tile{
						{ID: "p2-notion", Text: "Notion"},
						{ID: "p2-timer", Text: "timer"},
						{ID: "p2-inbox-zero", Text: "inbox zero"},
						{ID: "p2-standing-desk", Text: "standing desk"},
					},
				},
				{
					ID:          "soft-launch-of-a-personality",
					Name:        "Soft launch of a personality",
					Explanation: "A carefully casual set of props for becoming interesting online.",
					ColorIndex:  2,
					Tiles: []Tile{
						{ID: "p2-tote-bag", Text: "tote bag"},
						{ID: "p2-film-camera", Text: "film camera"},
						{ID: "p2-matcha", Text: "matcha"},
						{ID: "p2-tiny-sunglasses", Text: "tiny sunglasses"},
					},
				},
				{
					ID:          "rainy-cafe-main-character",
					Name:        "Rainy cafe main character",
					Explanation: "A window scene with just enough weather to justify the mood.",
					ColorIndex:  3,
					Tiles: []Tile{
						{ID: "p2-window-seat", Text: "window seat"},
						{ID: "p2-paperback", Text: "paperback"},
						{ID: "p2-jazz", Text: "jazz"},
						{ID: "p2-ceramic-mug", Text: "ceramic mug"},
					},
				},
			},
		},
		{
			ID:           "vibegrid-2026-06-04",
			PuzzleNumber: 3,
			PublishDate:  "2026-06-04",
			Status:       PuzzleStatusPublished,
			Difficulty:   DifficultyMedium,
			Origin:       OriginEditorial,
			Groups: []PuzzleGroup{
				{
					ID:          "group-chat-currently-on-fire",
					Name:        "Group chat currently on fire",
					Explanation: "Digital smoke, social panic, and one person typing too long.",
					ColorIndex:  0,
					Tiles: []Tile{
						{ID: "p3-screenshot", Text: "screenshot"},
						{ID: "p3-typing-dots", Text: "typing dots"},
						{ID: "p3-voice-note", Text: "voice note"},
						{ID: "p3-side-eye", Text: "side eye"},
					},
				},
				{
					ID:          "premium-mediocrity",
					Name:        "Premium mediocrity",
					Explanation: "A night out priced like taste and assembled like a template.",
					ColorIndex:  1,
					Tiles: []Tile{
						{ID: "p3-truffle-fries", Text: "truffle fries"},
						{ID: "p3-rooftop", Text: "rooftop"},
						{ID: "p3-small-plates", Text: "small plates"},
						{ID: "p3-qr-menu", Text: "QR menu"},
					},
				},
				{
					ID:          "wellness-rebrand",
					Name:        "Wellness rebrand",
					Explanation: "Ordinary recovery dressed up as a new identity system.",
					ColorIndex:  2,
					Tiles: []Tile{
						{ID: "p3-magnesium", Text: "magnesium"},
						{ID: "p3-breathwork", Text: "breathwork"},
						{ID: "p3-sunrise", Text: "sunrise"},
						{ID: "p3-linen-set", Text: "linen set"},
					},
				},
				{
					ID:          "deadline-theater",
					Name:        "Deadline theater",
					Explanation: "The performance of control right before the real panic begins.",
					ColorIndex:  3,
					Tiles: []Tile{
						{ID: "p3-deck", Text: "deck"},
						{ID: "p3-caffeine", Text: "caffeine"},
						{ID: "p3-calendar-hold", Text: "calendar hold"},
						{ID: "p3-polite-panic", Text: "polite panic"},
					},
				},
			},
		},
		{
			ID:           "vibegrid-2026-06-05",
			PuzzleNumber: 4,
			PublishDate:  "2026-06-05",
			Status:       PuzzleStatusPublished,
			Difficulty:   DifficultyMedium,
			Origin:       OriginEditorial,
			Groups: []PuzzleGroup{
				{
					ID:          "bangalore-founder-starter-pack",
					Name:        "Bangalore founder starter pack",
					Explanation: "Ambition, caffeine, mobility, and the deck that explains it all.",
					ColorIndex:  0,
					Tiles: []Tile{
						{ID: "p4-pitch-deck", Text: "pitch deck"},
						{ID: "p4-filter-coffee", Text: "filter coffee"},
						{ID: "p4-scooter", Text: "scooter"},
						{ID: "p4-seed-round", Text: "seed round"},
					},
				},
				{
					ID:          "monsoon-commute",
					Name:        "Monsoon commute",
					Explanation: "A journey measured in damp socks and civic resignation.",
					ColorIndex:  1,
					Tiles: []Tile{
						{ID: "p4-puddle", Text: "puddle"},
						{ID: "p4-umbrella", Text: "umbrella"},
						{ID: "p4-delayed-train", Text: "delayed train"},
						{ID: "p4-wet-socks", Text: "wet socks"},
					},
				},
				{
					ID:          "sunday-reset",
					Name:        "Sunday reset",
					Explanation: "Tiny domestic order before the week gets ideas.",
					ColorIndex:  2,
					Tiles: []Tile{
						{ID: "p4-clean-sheets", Text: "clean sheets"},
						{ID: "p4-meal-prep", Text: "meal prep"},
						{ID: "p4-face-mask", Text: "face mask"},
						{ID: "p4-laundry", Text: "laundry"},
					},
				},
				{
					ID:          "overpriced-minimalism",
					Name:        "Overpriced minimalism",
					Explanation: "A lack of things, billed as a point of view.",
					ColorIndex:  3,
					Tiles: []Tile{
						{ID: "p4-concrete-lamp", Text: "concrete lamp"},
						{ID: "p4-linen-menu", Text: "linen menu"},
						{ID: "p4-tiny-chair", Text: "tiny chair"},
						{ID: "p4-blank-logo", Text: "blank logo"},
					},
				},
			},
		},
		{
			ID:           "vibegrid-2026-06-06",
			PuzzleNumber: 5,
			PublishDate:  "2026-06-06",
			Status:       PuzzleStatusPublished,
			Difficulty:   DifficultyMedium,
			Origin:       OriginEditorial,
			Groups: []PuzzleGroup{
				{
					ID:          "corporate-seance",
					Name:        "Corporate seance",
					Explanation: "Everyone gathers to summon clarity and mostly gets jargon.",
					ColorIndex:  0,
					Tiles: []Tile{
						{ID: "p5-calendar-invite", Text: "calendar invite"},
						{ID: "p5-alignment", Text: "alignment"},
						{ID: "p5-stakeholders", Text: "stakeholders"},
						{ID: "p5-circling-back", Text: "circling back"},
					},
				},
				{
					ID:          "cool-aunt-energy",
					Name:        "Cool aunt energy",
					Explanation: "Advice, glamour, and a life that clearly has footnotes.",
					ColorIndex:  1,
					Tiles: []Tile{
						{ID: "p5-red-lipstick", Text: "red lipstick"},
						{ID: "p5-old-records", Text: "old records"},
						{ID: "p5-silk-scarf", Text: "silk scarf"},
						{ID: "p5-wisdom", Text: "wisdom"},
					},
				},
				{
					ID:          "host-mode-unlocked",
					Name:        "Host mode unlocked",
					Explanation: "The apartment is pretending it was always this composed.",
					ColorIndex:  2,
					Tiles: []Tile{
						{ID: "p5-playlist", Text: "playlist"},
						{ID: "p5-candles", Text: "candles"},
						{ID: "p5-ice-bucket", Text: "ice bucket"},
						{ID: "p5-coat-pile", Text: "coat pile"},
					},
				},
				{
					ID:          "phone-battery-panic",
					Name:        "Phone battery panic",
					Explanation: "A modern survival drama with a very small percentage left.",
					ColorIndex:  3,
					Tiles: []Tile{
						{ID: "p5-two-percent", Text: "2 percent"},
						{ID: "p5-charger", Text: "charger"},
						{ID: "p5-airplane-mode", Text: "airplane mode"},
						{ID: "p5-power-bank", Text: "power bank"},
					},
				},
			},
		},
		{
			ID:           "vibegrid-2026-06-07",
			PuzzleNumber: 6,
			PublishDate:  "2026-06-07",
			Status:       PuzzleStatusPublished,
			Difficulty:   DifficultyMedium,
			Origin:       OriginEditorial,
			Groups: []PuzzleGroup{
				{
					ID:          "museum-date-signals",
					Name:        "Museum date signals",
					Explanation: "Quiet flirting under institutional lighting.",
					ColorIndex:  0,
					Tiles: []Tile{
						{ID: "p6-tote", Text: "tote"},
						{ID: "p6-whispering", Text: "whispering"},
						{ID: "p6-wall-text", Text: "wall text"},
						{ID: "p6-slow-walk", Text: "slow walk"},
					},
				},
				{
					ID:          "breakup-ecosystem",
					Name:        "Breakup ecosystem",
					Explanation: "Objects that suddenly become emotionally load-bearing.",
					ColorIndex:  1,
					Tiles: []Tile{
						{ID: "p6-hoodie", Text: "hoodie"},
						{ID: "p6-playlist", Text: "playlist"},
						{ID: "p6-unread-thread", Text: "unread thread"},
						{ID: "p6-ice-cream", Text: "ice cream"},
					},
				},
				{
					ID:          "fancy-picnic-logistics",
					Name:        "Fancy picnic logistics",
					Explanation: "The charming outdoor meal that requires a surprising amount of gear.",
					ColorIndex:  2,
					Tiles: []Tile{
						{ID: "p6-blanket", Text: "blanket"},
						{ID: "p6-olives", Text: "olives"},
						{ID: "p6-baguette", Text: "baguette"},
						{ID: "p6-bottle-opener", Text: "bottle opener"},
					},
				},
				{
					ID:          "inbox-survival-kit",
					Name:        "Inbox survival kit",
					Explanation: "Tools for turning digital dread into tidy little rows.",
					ColorIndex:  3,
					Tiles: []Tile{
						{ID: "p6-filter", Text: "filter"},
						{ID: "p6-label", Text: "label"},
						{ID: "p6-archive", Text: "archive"},
						{ID: "p6-snooze", Text: "snooze"},
					},
				},
			},
		},
		{
			ID:           "vibegrid-2026-06-08",
			PuzzleNumber: 7,
			PublishDate:  "2026-06-08",
			Status:       PuzzleStatusPublished,
			Difficulty:   DifficultyHard,
			Origin:       OriginEditorial,
			Groups: []PuzzleGroup{
				{
					ID:          "soft-villain-era",
					Name:        "Soft villain era",
					Explanation: "A tasteful menace board for people who own exactly one dramatic outfit.",
					ColorIndex:  0,
					Tiles: []Tile{
						{ID: "p7-black-turtleneck", Text: "black turtleneck"},
						{ID: "p7-chess", Text: "chess"},
						{ID: "p7-espresso", Text: "espresso"},
						{ID: "p7-locked-door", Text: "locked door"},
					},
				},
				{
					ID:          "tiny-apartment-luxury",
					Name:        "Tiny apartment luxury",
					Explanation: "Small-space proof that comfort is mostly curation.",
					ColorIndex:  1,
					Tiles: []Tile{
						{ID: "p7-good-lamp", Text: "good lamp"},
						{ID: "p7-fresh-basil", Text: "fresh basil"},
						{ID: "p7-linen-towel", Text: "linen towel"},
						{ID: "p7-speaker", Text: "speaker"},
					},
				},
				{
					ID:          "bad-idea-origin-story",
					Name:        "Bad idea origin story",
					Explanation: "The innocent setup right before future-you has questions.",
					ColorIndex:  2,
					Tiles: []Tile{
						{ID: "p7-tequila", Text: "tequila"},
						{ID: "p7-group-chat", Text: "group chat"},
						{ID: "p7-last-train", Text: "last train"},
						{ID: "p7-borrowed-jacket", Text: "borrowed jacket"},
					},
				},
				{
					ID:          "morning-person-propaganda",
					Name:        "Morning person propaganda",
					Explanation: "A lifestyle pitch delivered before everyone else is conscious.",
					ColorIndex:  3,
					Tiles: []Tile{
						{ID: "p7-sunrise-run", Text: "sunrise run"},
						{ID: "p7-overnight-oats", Text: "overnight oats"},
						{ID: "p7-cold-shower", Text: "cold shower"},
						{ID: "p7-planner", Text: "planner"},
					},
				},
			},
		},
		{
			ID:           "vibegrid-2026-06-09",
			PuzzleNumber: 8,
			PublishDate:  "2026-06-09",
			Status:       PuzzleStatusPublished,
			Difficulty:   DifficultyMedium,
			Origin:       OriginEditorial,
			Groups: []PuzzleGroup{
				{
					ID:          "remote-work-mirage",
					Name:        "Remote work mirage",
					Explanation: "The dream of freedom, still somehow involving status lights.",
					ColorIndex:  0,
					Tiles: []Tile{
						{ID: "p8-beach-wifi", Text: "beach wifi"},
						{ID: "p8-laptop-stand", Text: "laptop stand"},
						{ID: "p8-status-green", Text: "status green"},
						{ID: "p8-muted-mic", Text: "muted mic"},
					},
				},
				{
					ID:          "wedding-guest-survival",
					Name:        "Wedding guest survival",
					Explanation: "Tiny emergency supplies for a long sentimental evening.",
					ColorIndex:  1,
					Tiles: []Tile{
						{ID: "p8-safety-pin", Text: "safety pin"},
						{ID: "p8-spare-flats", Text: "spare flats"},
						{ID: "p8-tissue", Text: "tissue"},
						{ID: "p8-envelope", Text: "envelope"},
					},
				},
				{
					ID:          "dad-vacation-mode",
					Name:        "Dad vacation mode",
					Explanation: "An itinerary of practical confidence before 8 a.m.",
					ColorIndex:  2,
					Tiles: []Tile{
						{ID: "p8-map", Text: "map"},
						{ID: "p8-cap", Text: "cap"},
						{ID: "p8-early-breakfast", Text: "early breakfast"},
						{ID: "p8-hotel-lobby", Text: "hotel lobby"},
					},
				},
				{
					ID:          "algorithm-made-me-buy-it",
					Name:        "Algorithm made me buy it",
					Explanation: "Useful-adjacent objects discovered during a weak scrolling moment.",
					ColorIndex:  3,
					Tiles: []Tile{
						{ID: "p8-serum", Text: "serum"},
						{ID: "p8-mini-blender", Text: "mini blender"},
						{ID: "p8-cable-organizer", Text: "cable organizer"},
						{ID: "p8-weighted-blanket", Text: "weighted blanket"},
					},
				},
			},
		},
		{
			ID:           "vibegrid-2026-06-10",
			PuzzleNumber: 9,
			PublishDate:  "2026-06-10",
			Status:       PuzzleStatusPublished,
			Difficulty:   DifficultyHard,
			Origin:       OriginEditorial,
			Groups: []PuzzleGroup{
				{
					ID:          "bookstore-crush",
					Name:        "Bookstore crush",
					Explanation: "A quiet romantic subplot hiding between shelves.",
					ColorIndex:  0,
					Tiles: []Tile{
						{ID: "p9-staff-pick", Text: "staff pick"},
						{ID: "p9-tote-bag", Text: "tote bag"},
						{ID: "p9-margin-notes", Text: "margin notes"},
						{ID: "p9-rainy-aisle", Text: "rainy aisle"},
					},
				},
				{
					ID:          "founder-mode-bedtime",
					Name:        "Founder mode bedtime",
					Explanation: "Rest, but make it measurable, optimized, and faintly anxious.",
					ColorIndex:  1,
					Tiles: []Tile{
						{ID: "p9-inbox", Text: "inbox"},
						{ID: "p9-sleep-app", Text: "sleep app"},
						{ID: "p9-protein-shake", Text: "protein shake"},
						{ID: "p9-calendar-audit", Text: "calendar audit"},
					},
				},
				{
					ID:          "expensive-boredom",
					Name:        "Expensive boredom",
					Explanation: "A chic afternoon where nothing happens beautifully.",
					ColorIndex:  2,
					Tiles: []Tile{
						{ID: "p9-gallery", Text: "gallery"},
						{ID: "p9-spritz", Text: "spritz"},
						{ID: "p9-linen-suit", Text: "linen suit"},
						{ID: "p9-no-plans", Text: "no plans"},
					},
				},
				{
					ID:          "kitchen-confidence",
					Name:        "Kitchen confidence",
					Explanation: "The small cast of characters that makes dinner feel intentional.",
					ColorIndex:  3,
					Tiles: []Tile{
						{ID: "p9-garlic", Text: "garlic"},
						{ID: "p9-cast-iron", Text: "cast iron"},
						{ID: "p9-flaky-salt", Text: "flaky salt"},
						{ID: "p9-apron", Text: "apron"},
					},
				},
			},
		},
	}
}
